### ISSUE TITLE
Ligatures?

### ISSUE THREAD

**Issue by carlomunguia** [fonsecapeter/brass_mono#18]
Brass Mono is wonderful to code in.
I use languages daily that use operators/fat arrows that use them(=>, >=, etc.).

Any plans in the future to add ligatures to Brass Mono?
Would love to eventually see it with ligatures - that being said I know its a 50/50 split on font creators liking them in the first place. 

Thank you!

**Comment by fonsecapeter** [comment]
Thank you + sorry I didn't see your issue! 

I think that's a great idea and will definitely look into it – maybe just `<=`, `>=`, `==`, `!=`, `===`, !==` unless you have any other requests?

**Comment by carlomunguia** [comment]
Thanks for responding!

All of those work, but would also like to see -> & --> if possible.  Those 2 with the ones you listed cover my ligature use cases.

**Comment by fonsecapeter** [comment]
Sounds good! Have confirmed I am able to make ligatures, will go ahead and add all of those – looks like folks can just turn ligatures on/off wherever the font is used too so shouldn't be too controversial to add them in

Also apologies for my delay (and any more to come) I just work on this in my spare time 😄
